services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dentist_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      # ✅ เพิ่ม init script ถ้ามี
      - ./dentist_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentist-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: dentist_db
      SESSION_SECRET: your-secret-key-change-this
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
    # ✅ เพิ่ม volumes สำหรับ uploads เพื่อให้ persist data
    volumes:
      - ./public/uploads:/usr/src/app/public/uploads
      # ✅ Optional: mount source code สำหรับ development
      # - .:/usr/src/app
      # - /usr/src/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql-data: