warning: in the working copy of 'views/patient/appointment/book.ejs', LF will be replaced by CRLF the next time Git touches it
M	app.js
M	controller/admin.controller.js
M	controller/admin.slots.controller.js
M	controller/dentist.controller.js
M	controller/notification.controller.js
M	controller/patient.controller.js
M	routes/dentist.route.js
M	views/admin/appointment/admin-appointments.ejs
M	views/admin/appointment/appointment-detail.ejs
M	views/admin/dentists/admin-dentists.ejs
M	views/admin/treatment/admin-treatments.ejs
M	views/dentist/appointment-detail.ejs
M	views/dentist/appointments.ejs
M	views/dentist/dashboard.ejs
M	views/dentist/patient-detail.ejs
M	views/dentist/treatment-history-detail.ejs
M	views/patient/appointment/book.ejs
M	views/patient/change-password.ejs
M	views/patient/dentists/list.ejs
M	views/patient/edit-profile.ejs
M	views/patient/history/details.ejs
M	views/patient/history/list.ejs
M	views/patient/patient-dashboard.ejs
M	views/patient/profile.ejs
M	views/patient/treatments/details.ejs
M	views/patient/treatments/list.ejs
